# https://taskfile.dev
version: '3'
includes:
  edit: ../../taskfile-lib/edit.yaml

dotenv: ['{{.K8S_APPS}}/env.{{.ENV}}']
tasks:
  deploy:
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - kubectl create namespace kubeapps
      - helm install kubeapps --namespace kubeapps bitnami/kubeapps

      - kubectl create serviceaccount kubeapps-operator --namespace {{.NAMESPACE}}
      - kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator

  delete:
    cmds:
      - kubectl delete namespace kubeapps
      - kubectl delete serviceaccount kubeapps-operator --namespace {{.NAMESPACE}}

  get-secret:
    cmds:
      - kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo

  port-forward:
    cmds:
      - kubectl port-forward -n kubeapps svc/kubeapps --address 0.0.0.0 9093:80

  test:
    cmds:

  edit-cfg:
    cmds:
      - code-server /src/user/apps/k8s/kubeapps.yaml