# https://taskfile.dev
version: '3'

tasks:
  deploy:
    cmds:
      - >-
        helm repo add bitnami https://charts.bitnami.com/bitnami && \
        kubectl create namespace kubeapps && \
        helm install kubeapps --namespace kubeapps bitnami/kubeapps;

        kubectl create --namespace default serviceaccount kubeapps-operator && \
        kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator;

  delete:
    cmds:
      # TODO: finish
      - >-
        kubectl --namespace default delete

  get-secret:
    cmds:
      - >-
        kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo

  port-forward:
    cmds:
      - kubectl port-forward -n kubeapps svc/kubeapps --address 0.0.0.0 9093:80

  test:
    cmds:

  edit-cfg:
    cmds:
      - code-server /src/user/apps/k8s/kubeapps.yaml