# https://taskfile.dev
version: '3'
includes:
  edit: ../../taskfile-lib/edit.yaml

dotenv: ['{{.K8S_APPS}}/env.{{.ENV}}']
tasks:
  # https://github.com/bitnami/charts/tree/master/bitnami/redis/#installing-the-chart
  # TODO: test with name & full name overrides for all k8s objects including pv/pvc
  deploy:
    cmds:
      - >-
        helm install {{.NAMESPACE}}-redis bitnami/{{.APP_NAME}} \
          --set auth.enabled=false --set replica.replicaCount=0 \
          --set master.service.type=NodePort --set master.service.nodePorts.redis=6379 \
          --namespace {{.NAMESPACE}} --wait;
  delete:
    cmds:
      - helm delete {{.NAMESPACE}}-{{.APP_NAME}} --namespace {{.NAMESPACE}} --wait
  install-tools:
    cmds:
      - sudo apt -y install redis-tools
  test:
    cmds:
      #- echo {{.ENV}} {{.NAMESPACE}}
      - kubectl -n ${{.NAMESPACE}} get pods | grep {{.APP_NAME}}
      # test for redis cli
      - redis-cli -h 0.0.0.0 KEYS blah