# https://taskfile.dev
version: '3'
env:
  NAMESPACE: '{{.NAMESPACE | default "default"}}'

tasks:
  deploy:
    cmds:
      - helm install {{.NAMESPACE}}-mysql bitnami/mysql --set auth.rootPassword=root --set primary.service.type=NodePort --set primary.service.nodePort=3306
      # TODO: check for mysql named pod
      - kubectl wait --for=condition=ready --timeout=90s --all pods
  delete:
    cmds:
      - helm delete {{.NAMESPACE}}-mysql
  test:
    cmds:
      - kubectl get pods | grep mysql
      # from sarathy container
      - mysql -h sarathy -u root -proot -e 'show databases;'
      # from sarathy container's k8s cluster

  edit-cfg:
    cmds:
      - code-server /src/user/apps/k8s/dbs/mysql.yaml